### ISSUE TITLE
README could be more clear on how to create UPLOAD_ACCESS_KEY

### ISSUE THREAD

**Issue by topher200** [farski/serverless-transcribe#3]
The way the readme is written, it's a little confusing on how many s3 buckets one must create. The readme clearly says that you must create one (STACK_RESOURCES_BUCKET), but then it talks about providing access keys to a different bucket (MEDIA_BUCKET_IDENTIFIER). Does one have to create the second bucket to be to provide access keys to it? Or is there a way to generate the access keys without knowing the bucket ahead of time?

To resolve this, I'd do one of these things:
1. provide explicit instructions on how to generate UPLOAD_ACCESS_KEY
2. is it possible to have UPLOAD_ACCESS_KEY be generated by the cloudformation script instead? why does the user have to create the IAM role themselves at all?

**Comment by farski** [comment]
Great idea. The IAM user and access key are [now](https://github.com/farski/serverless-transcribe/commit/0f0f70de54b4909802010c1ac66af9131c464951) handled by the CloudFormation template.
