### ISSUE TITLE
{"message":null}

### ISSUE THREAD

**Issue by githubusr1** [farski/serverless-transcribe#5]
I tried your project, i used deploy.sh to install well, but when i use the output link of cloudformation to login,fill right user and password out, but finally it has no further page to let me upload file to transcribe it, just display {"message":null}, i dont know how to fix it, looking for help. thanks.

![image](https://user-images.githubusercontent.com/17020810/56727764-ea40c200-6783-11e9-9a57-de76026e9ce6.png)

**Comment by dariushazimi** [comment]
@githubusr1 
@farski 
I get the same message after I use the deploy.sh.
`{
"message": null
}`

**Comment by dariushazimi** [comment]
@githubusr1 Were you able to resolve it?

**Comment by farski** [comment]
@githubusr1 @dariushazimi That is generally what you will see if the HTTP Basic auth credentials are wrong. Are you sure you're entering them correctly?

**Comment by githubusr1** [comment]
@farski  i am sure the auth credentials are entered correctly.   maybe i need to think of adding blank before them or endcode them by base64,  do you have any method to debug it?

**Comment by githubusr1** [comment]
@dariushazimi  i have no further progress yet. u?

**Comment by farski** [comment]
@githubusr1 You can see in the [authorizer function](https://github.com/farski/serverless-transcribe/blob/master/lambdas/StaticWebsiteAuthorizerFunction/lambda_function.py), which is what handles the HTTP basic auth, that the implementation is very simple. For example, it's just doing a [`split`](https://github.com/farski/serverless-transcribe/blob/master/lambdas/StaticWebsiteAuthorizerFunction/lambda_function.py#L19) on the decoded header value, so if your username included a `:` this would probably break.

You could add some logging to that function to get a better sense of what it's doing.

**Comment by dariushazimi** [comment]
@githubusr1 @farski 
I have a simple user id and password shown here:
```
STACK_RESOURCES_BUCKET=abcdresourcebucket # A pre-existing S3 bucket where resources needed to launch the stack can be put
MEDIA_BUCKET_IDENTIFIER=abcdamediabucketidentifier # An identifier used to name the bucket where media will be uploaded
BASIC_AUTH_USERNAME=userx1 # Username for HTTP Basic auth of the upload webpage
BASIC_AUTH_PASSWORD=passwordx1 # Password for HTTP Basic auth of the upload webpage
NOTIFICATION_SOURCE_EMAIL_ADDRESS=email@me.com # The email address from which transcripts are sent
```

deployment completes without any issues but I still get the:
`{ "message": null }`

I looked at the authorizer function and I don't see any issue that would result in this, considering my user id and pass don't contain any special characters` " : "`

**Comment by farski** [comment]
@dariushazimi Could you share the full HTTP response of the page you're getting, including status code and headers? Or if possible, could you share the URL for the site? You could email it or DM me on Twitter.

**Comment by dariushazimi** [comment]
@farski Good news. it works. Why? don't know. Removed the entire env from AWS. Redeployed and I get the user interface. Which is great. 

Now I uploaded a small 10 min video and as soon as the upload was completed I get this response.

`<Error>
<Code>AccessDenied</Code>
<Message>
Invalid according to Policy: Policy Condition failed: ["starts-with", "$Content-Type", "audio/"]
</Message>
<RequestId>16839082886D08F3</RequestId>
<HostId>
5rEgrEN3HIyNty2CLkuxaDL6EUv/X1Kn0OrFw4oIAW8JRpuHinUfq92PyADc6oqVB547oN8dkXI=
</HostId>
</Error>`

Could it be S3 related? I just created an s3 bucket with no additional settings except "Versioning enabled". 

Any idea?

**Comment by dariushazimi** [comment]
I would close this ticket as I suspect (as you had mentioned ) that the user id and password was incorrect. But the issue with access denied remains:
`<Error> <Code>AccessDenied</Code> <Message> Invalid according to Policy: Policy Condition failed: ["starts-with", "$Content-Type", "audio/"] </Message> <RequestId>16839082886D08F3</RequestId> <HostId> 5rEgrEN3HIyNty2CLkuxaDL6EUv/X1Kn0OrFw4oIAW8JRpuHinUfq92PyADc6oqVB547oN8dkXI= </HostId> </Error>`

**Comment by dariushazimi** [comment]
@githubusr1 
Make sure you are using the correct user id and password. I redeployed the solution and used the user id and pass and it I get the proper link. I suspect I was using the wrong id, password. It is always the user error (at least in my case)  👍

**Comment by farski** [comment]
I believe Amazon Transcribe only supports audio files, so this uploader also only accepts audio files. If they've added video support I missed the announcement
