### ISSUE TITLE
AccessDenied</Code> <Message> Invalid according to Policy:

### ISSUE THREAD

**Issue by dariushazimi** [farski/serverless-transcribe#6]
@farski  After creating an S3 bucket with versioning enabled deployed the solution.
I get a link and when I fill in the email, set speackers to one and upload a short video. 
As soon as I click on upload I get the following error:

`<Error> <Code>AccessDenied</Code> <Message> Invalid according to Policy: Policy Condition failed: ["starts-with", "$Content-Type", "audio/"] </Message> <RequestId>16839082886D08F3</RequestId> <HostId> 5rEgrEN3HIyNty2CLkuxaDL6EUv/X1Kn0OrFw4oIAW8JRpuHinUfq92PyADc6oqVB547oN8dkXI= </HostId> </Error>`

**Comment by farski** [comment]
@dariushazimi I believe Amazon Transcribe only supports audio files, so this uploader also only accepts audio files. A quick look at the docs make it seem like that's still the case. You'll have to strip the audio into a separate file before you upload.

**Comment by dariushazimi** [comment]
@farski 
Yes transcribe from AWS does support video files.

**Comment by farski** [comment]
@dariushazimi Do you have a list of formats that it supports?

**Comment by farski** [comment]
@dariushazimi The API only supports these formats: mp3, mp4, wav, flac based on the docs

**Comment by dariushazimi** [comment]
Correction. AWS Transcribe does support audio but I have tried the media solution analysis which supports video as well. Basically separates audio from video and does the transcription using the Transcribe. Works perfect but it has a lot of other services which I don't need and can be costly.

**Comment by dariushazimi** [comment]
Have you looked at the media analysis solution?

**Comment by farski** [comment]
Yes I have. It looks like a good solution if you need a full featured analysis product. I only needed transcription, with a lightweight UI and that I could easily give access to others.

**Comment by dariushazimi** [comment]
Update: Uploaded an audio file successfully. But where is the transcription output ? :) I don't see any output on the page? checked the bucket and it is also empty?!!!

ps. Tried to DM you on twitter but I get: Sorry you can't message this person !!

**Comment by sachin10101998** [comment]
Can we process mp4 to mp3 conversion in lambda iteslf and allow people to upload mp4?

**Comment by farski** [comment]
@sachin10101998 ~Audio MP4 files should without requiring any conversion. If you're needing video MP4 files, those should also work but currently aren't allowed by the upload validation step. I can work on fixing that.~

Actually sorry, I was confusing this with a different AWS service. Currently AWS Transcribe only supports audio files. Both AWS Transcribe and this app should allow for MP4 audio files, though. If you are having issues with that please open a new issue.
