### ISSUE TITLE
Support for channel identification

### ISSUE THREAD

**Issue by fienen** [farski/serverless-transcribe#8]
Would it be possible to create a flag/checkbox on the front end when uploading a file to enable channel identification for the transcription job on a file? For instance, if I output a podcast episode with myself on the left channel and my cohost on the right, Amazon Transcribe has an easier time interpreting each voice separately.

Ref: https://docs.aws.amazon.com/transcribe/latest/dg/how-channel-id.html

**Comment by farski** [comment]
@fienen Sorry I never responded; I didn't get a notification when you opened this issue so I only saw it today. I just pushed an update that adds an options for using channel identification.

**Comment by fienen** [comment]
Thanks! Can't wait to try it!
